### ISSUE TITLE
[SPIKE-16]: Verify which CRUDs are working as expected and which other don't do it

### ISSUE THREAD

**Issue by christianahvilla** [christianahvilla/surveys-cahv#16]

**Comment by christianahvilla** [comment]
1. As PM I would like to see a list with the CRUDS are working and which don't do it. 
2. Also the list must contain the following points: 
3. Endpoint, Entity (Survey, Client, etc.), Type or interfaces necessary.
4. This list should be a README.md

**Comment by jFroylan-Cal** [comment]
# Clients 
- Edit 
--Click on save dont do nothing just refresh the page
- Delete
-- Return 404 error page
-- Dont send any request

# Users
- Create 
-- A message is needed when the user does not put the password in the correct format
- Delete
--Return 404 error page
--Dont send any request

# Surveys
- Create
-- After creating a survey return to the error page 404
- Edit 
-- Edit is not working
- Delete
--Return 404 error page
--Dont send any request

# Questions
- Create
-- Needed the select for the survey 
- Edit
-- Return 404 error page
- Delete
--Return 404 error page
--Dont send any request

# Answers
- CRUD needed

# Results
- CRUD needed

# Suveryed
- CRUD needed

# Paths
- CRUD needed

**Comment by christianahvilla** [comment]
What is `Resulta` ?
I believe it is missing entity `Paths`

**Comment by christianahvilla** [comment]
Also it is missing a table for entity `Surveyed`.

## Notes
- You can get more details here [ENCUESTAS-API](https://encuestas-api.onrender.com/api) 
- Any question please let me know

**Comment by jFroylan-Cal** [comment]
I already made the corrections, I only have the suggestion to change the word paths to tours this to avoid confusion

**Comment by christianahvilla** [comment]
> I already made the corrections, I only have the suggestion to change the word paths to tours this to avoid confusion

Greate one, changed and thaks :+1:
